const fs = require('fs');
const path = require('path');

const intros = {
  "United States": "When tracking fitness and nutritional goals in the United States, understanding your Total Daily Energy Expenditure (TDEE) is absolutely essential. The standard American diet is often highly calorie-dense, and relying on broad national averages can lead to unintentional weight gain. Our US-focused TDEE calculator natively supports imperial measurements, allowing you to seamlessly enter your weight in pounds and height in feet and inches without complicated conversions. By utilizing the medically validated Mifflin-St Jeor formula, this tool provides you with a highly accurate metabolic baseline. Whether you are following popular American dietary trends like keto, intermittent fasting, or a standard macro-tracking approach, establishing an exact caloric target tailored to your unique age, weight, and daily activity level is the most critical first step toward sustainable weight management and overall metabolic health.",
  "United Kingdom": "For residents of the United Kingdom, achieving healthy weight management requires a precise understanding of your Total Daily Energy Expenditure (TDEE). While NHS guidelines provide general recommendations for daily caloric intake and suggest a 500 to 600 calorie deficit for safe weight loss, these broad averages do not account for your specific body composition or lifestyle. Our UK-focused TDEE calculator bridges this gap by offering a fully localized experience that seamlessly supports both metric measurements and the traditional imperial stone and pounds. By leveraging the scientifically validated Mifflin-St Jeor equation, this tool calculates your exact maintenance calories and provides tailored macronutrient splits. Whether you are navigating the calorie-dense options of traditional British cuisine or adhering to a strict gym routine, knowing your exact TDEE ensures your nutritional approach is based on concrete science rather than guesswork.",
  "Canada": "Navigating nutritional goals in Canada is vastly simplified when you understand your Total Daily Energy Expenditure (TDEE). Health Canada provides excellent generalized dietary guidelines, emphasizing whole foods and active living, but individual caloric needs vary drastically based on your unique body metrics and activity level. Our Canada-optimized TDEE calculator is designed to seamlessly support both the official metric system (kilograms and centimeters) used on Canadian nutrition labels, as well as the imperial system (pounds) commonly used for personal body weight. Whether you are extremely active during the winter months participating in hockey and skiing, or maintaining a moderate exercise routine, this tool uses the clinical-grade Mifflin-St Jeor equation to pinpoint your exact caloric baseline. This level of precision is fundamental for structuring a safe, effective calorie deficit for fat loss or a surplus for muscle gain.",
  "Australia": "In Australia, a nation characterized by an incredibly active, outdoor-centric lifestyle, accurately calculating your Total Daily Energy Expenditure (TDEE) is crucial for optimal health and athletic performance. The Australian Dietary Guidelines suggest average daily intakes, but the significant variations in daily activity—from regular surfing and hiking to intense gym sessions—demand a personalized approach to nutrition. Our Australia-specific TDEE calculator uses the globally validated Mifflin-St Jeor formula and natively supports the metric system (kilograms and centimeters), ensuring perfect alignment with local food packaging and nutritional labels. By determining your precise maintenance calories, you can confidently navigate Australia's robust food culture while making informed decisions about portion sizes and macronutrient distribution. This targeted approach is the cornerstone of sustainable weight loss, muscle development, and long-term metabolic health.",
  "India": "Understanding your Total Daily Energy Expenditure (TDEE) is uniquely important in India, where traditional diets are incredibly diverse, rich in complex carbohydrates, and often feature calorie-dense cooking methods. The Indian Council of Medical Research (ICMR) provides baseline dietary guidelines, but individual caloric requirements can fluctuate massively depending on your specific height, weight, and lifestyle. Our India-focused TDEE calculator utilizes the highly accurate Mifflin-St Jeor equation and supports metric measurements (kilograms and centimeters) to deliver a perfectly tailored caloric baseline. This precision is essential for Indian users looking to balance the nutritional benefits of traditional regional cuisines with modern fitness goals, such as managing a healthy BMI or reducing body fat. By calculating your exact daily energy needs, you can easily adjust your intake of local staples while maintaining a healthy, sustainable diet plan.",
  "Germany": "For users in Germany, achieving precise fitness and weight management goals begins with a thorough understanding of your Total Daily Energy Expenditure (TDEE). While the German Nutrition Society (DGE) provides excellent general guidelines for a balanced diet and regular physical activity, individual metabolic rates require a personalized calculation rather than reliance on national averages. Our Germany-optimized TDEE calculator is fully aligned with the metric system, allowing you to use kilograms and centimeters for flawless integration with European nutritional labels. Driven by the gold-standard Mifflin-St Jeor formula, this tool accurately accounts for your specific age, gender, and activity level. Whether you are participating in Germany's vibrant outdoor sports culture or simply looking to balance your intake of rich traditional foods, knowing your exact TDEE is the most effective way to manage your caloric deficit or surplus safely.",
  "UAE": "In the United Arab Emirates, where extreme summer temperatures often shift physical activity indoors and cultural practices like Ramadan significantly alter eating patterns, understanding your Total Daily Energy Expenditure (TDEE) is vital. The UAE boasts a incredibly diverse expat population and a thriving fitness culture, meaning generalized dietary advice often falls short of individual needs. Our UAE-focused TDEE calculator uses the globally validated Mifflin-St Jeor equation and operates seamlessly in metric units (kilograms and centimeters). By identifying your precise maintenance calories, you can accurately plan your meals—whether you are structuring suhoor and iftar during fasting months, or balancing the rich, calorie-dense foods common in Middle Eastern and international cuisines. This scientific approach ensures your nutrition aligns perfectly with your specific lifestyle, body composition, and long-term health objectives.",
  "France": "In France, where the culinary culture famously emphasizes high-quality ingredients, rich flavors, and moderate portion sizes, knowing your Total Daily Energy Expenditure (TDEE) is an incredibly powerful tool for maintaining a healthy lifestyle. While the traditional French diet naturally supports metabolic health, individual caloric needs can vary wildly depending on your specific daily activity, age, and body composition. Our France-optimized TDEE calculator uses the scientifically validated Mifflin-St Jeor formula and natively supports the metric system (kilograms and centimeters) for perfect consistency with European nutritional standards. By establishing your exact caloric baseline, you can continue to enjoy culturally significant, calorie-dense foods like artisan cheeses and wine in moderation, without compromising your fitness goals. This precise, data-driven approach is essential for anyone looking to achieve sustainable weight loss or muscle maintenance.",
  "Brazil": "Brazil's incredibly strong fitness culture and vibrant, active lifestyle make understanding your Total Daily Energy Expenditure (TDEE) an essential component of any health journey. While traditional Brazilian staples like rice and beans provide excellent foundational nutrition, the widespread popularity of calorie-dense treats like fully loaded açaí bowls requires careful dietary management. Our Brazil-focused TDEE calculator is perfectly adapted for the metric system, allowing you to input kilograms and centimeters for accurate, localized results. Utilizing the highly respected Mifflin-St Jeor equation, this tool calculates your exact daily maintenance calories, factoring in your specific age, weight, and activity level—from intense gym sessions to weekend football matches. This precise calculation empowers you to navigate Brazil's dynamic food culture while maintaining a structured, science-backed approach to fat loss, muscle gain, or healthy weight maintenance.",
  "Mexico": "For users in Mexico, determining your precise Total Daily Energy Expenditure (TDEE) is a critical step toward achieving long-term health and fitness goals. Traditional Mexican cuisine is rich in nutrient-dense ingredients like beans, corn, and lean proteins, but many popular preparations and beverages can be unexpectedly high in calories. Our Mexico-optimized TDEE calculator utilizes the medically validated Mifflin-St Jeor formula and natively supports the metric system (kilograms and centimeters), ensuring your results align perfectly with local nutritional labeling. Additionally, this tool helps you account for environmental factors, such as the slightly elevated metabolic rates experienced by those living at high altitudes in cities like Mexico City. By identifying your exact daily caloric needs, you can enjoy the vibrant flavors of Mexican food while effectively managing your weight through a targeted, science-backed nutritional strategy.",
  "South Africa": "In South Africa, a nation celebrated for its intense sporting culture and active outdoor lifestyle, accurately calculating your Total Daily Energy Expenditure (TDEE) is fundamental to achieving your health and fitness objectives. The unique South African cultural landscape, particularly the popularity of the calorie-dense braai, makes relying on broad dietary averages ineffective for personal weight management. Our South Africa-focused TDEE calculator is fully optimized for metric measurements (kilograms and centimeters) and uses the clinical-grade Mifflin-St Jeor equation to deliver an exact metabolic baseline. Whether you are training for rugby, participating in endurance sports, or simply looking to manage your weight effectively, knowing your precise daily calorie target allows you to balance traditional cultural meals with your specific macronutrient requirements. This evidence-based approach is crucial for sustainable fat loss and overall metabolic health.",
  "New Zealand": "For residents of New Zealand, where an active, outdoor-oriented lifestyle is deeply ingrained in the culture, understanding your precise Total Daily Energy Expenditure (TDEE) is the key to unlocking your fitness potential. While the New Zealand Ministry of Health provides excellent baseline dietary guidelines, your individual caloric needs are heavily influenced by your specific body metrics and your participation in high-energy activities like tramping, rugby, or surfing. Our New Zealand-optimized TDEE calculator utilizes the scientifically validated Mifflin-St Jeor formula and natively supports the metric system (kilograms and centimeters) for seamless integration with local nutritional data. By pinpointing your exact maintenance calories, you can make informed decisions about your daily intake, perfectly balancing New Zealand's world-class, calorie-dense dairy products and traditional meals with your specific weight loss, maintenance, or muscle-building goals."
};

function processFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  
  let content = fs.readFileSync(filePath, 'utf-8');
  let changed = false;

  // 1. Update CountryPage definition to accept 'intro'
  if (content.includes('const CountryPage = ({ country, code, unit, titleFocus, desc, tips, slug, cities, faqs }) => {')) {
    content = content.replace(
      'const CountryPage = ({ country, code, unit, titleFocus, desc, tips, slug, cities, faqs }) => {',
      'const CountryPage = ({ country, code, unit, titleFocus, desc, intro, tips, slug, cities, faqs }) => {'
    );
    changed = true;
  }
  
  // 2. Add intro render to CountryPage
  if (content.includes('<h1>TDEE Calculator {country}</h1>') && !content.includes('{intro && <p style={{ marginTop: \'1.5rem\'')) {
    content = content.replace(
      '<h1>TDEE Calculator {country}</h1>\n          <p>{desc}</p>',
      '<h1>TDEE Calculator {country}</h1>\n          <p>{desc}</p>\n          {intro && <p style={{ marginTop: \'1.5rem\', fontSize: \'1.05rem\', lineHeight: \'1.7\', textAlign: \'left\', background: \'var(--card)\', border: \'1px solid var(--border)\', padding: \'1.5rem\', borderRadius: \'var(--r-lg)\' }}>{intro}</p>}'
    );
    changed = true;
  }

  // 3. Inject the intro prop into the usages
  for (const [countryName, introText] of Object.entries(intros)) {
    const regex = new RegExp(`(<CountryPage[^>]*?country="${countryName}"[^>]*?)>`);
    if (content.match(regex)) {
      if (!content.includes(`intro="${introText.substring(0, 20)}`)) {
        content = content.replace(regex, `$1\n  intro="${introText}">`);
        changed = true;
      }
    }
  }

  if (changed) {
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log('Injected intros in', filePath);
  }
}

const appDir = path.join(__dirname, 'app');
const dirs = fs.readdirSync(appDir);

dirs.forEach(dir => {
  if (dir.startsWith('tdee-calculator-')) {
    const clientPath = path.join(appDir, dir, 'ClientComponent.jsx');
    processFile(clientPath);
  }
});
