/** @type {() => import('next').MetadataRoute.Robots} */
export default function robots() {
  return {
    rules: [
      {
        userAgent: 'Mediapartners-Google',
        allow: '/',
      },
      {
        userAgent: '*',
        allow: [
          '/',
          '/tdee-calculator',
          '/bmr-calculator',
          '/bmi-calculator',
          '/macro-calculator',
          '/calorie-calculator',
          '/calorie-deficit',
          '/body-fat-calculator',
          '/protein-calculator',
          '/water-intake-calculator',
          '/lean-body-mass-calculator',
          '/ideal-weight',
          '/army-body-fat-calculator',
          '/keto-macro-calculator',
          '/one-rep-max-calculator',
          '/calories-burned-calculator',
          '/weight-loss-timeline',
          '/healthy-weight-calculator',
          '/target-heart-rate-calculator',
          '/body-type-calculator',
          '/body-surface-area-calculator',
          '/bac-calculator',
          '/carbohydrate-calculator',
          '/fat-intake-calculator',
          '/gfr-calculator',
          '/pace-calculator',
          '/intermittent-fasting-calculator',
          '/guess-calories-game',
          '/sleep-calculator',
          '/waist-to-hip-ratio-calculator',
          '/creatine-calculator',
          '/vo2-max-calculator',
          '/pregnancy-calculator',
          '/pregnancy-weight-gain-calculator',
          '/pregnancy-conception-calculator',
          '/due-date-calculator',
          '/ovulation-calculator',
          '/conception-calculator',
          '/period-calculator',
          '/tdee-calculator-us',
          '/tdee-calculator-uk',
          '/tdee-calculator-canada',
          '/tdee-calculator-australia',
          '/tdee-calculator-new-zealand',
          '/tdee-calculator-germany',
          '/tdee-calculator-france',
          '/tdee-calculator-india',
          '/tdee-calculator-uae',
          '/tdee-calculator-nigeria',
          '/tdee-calculator-philippines',
          '/tdee-calculator-russia',
          '/tdee-calculator-mexico',
          '/tdee-calculator-brazil',
          '/tdee-calculator-south-africa',
        ],
        disallow: ['/api/', '/_next/', '/x-admin-settings', '/admin'],
      },
    ],
    sitemap: 'https://tdee.tech/sitemap.xml',
    host: 'https://tdee.tech',
  };
}
