/** @type {() => import('next').MetadataRoute.Sitemap} */
export default function sitemap() {
  const baseUrl = 'https://tdee.tech';
  const now = new Date().toISOString();

  const routes = [
    { url: '/', priority: 1.0, changeFrequency: 'daily' },
    { url: '/tdee-calculator', priority: 1.0, changeFrequency: 'weekly' },
    { url: '/bmi-calculator', priority: 0.9, changeFrequency: 'weekly' },
    { url: '/macro-calculator', priority: 0.9, changeFrequency: 'weekly' },
    { url: '/bmr-calculator', priority: 0.9, changeFrequency: 'weekly' },
    { url: '/calorie-deficit', priority: 0.9, changeFrequency: 'weekly' },
    { url: '/calorie-calculator', priority: 0.9, changeFrequency: 'weekly' },
    { url: '/body-fat-calculator', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/ideal-weight', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/protein-calculator', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/water-intake-calculator', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/lean-body-mass-calculator', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/army-body-fat-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/keto-macro-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/one-rep-max-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/calories-burned-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/weight-loss-timeline', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/healthy-weight-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/target-heart-rate-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/body-type-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/body-surface-area-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/bac-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/carbohydrate-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/fat-intake-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/gfr-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/pace-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/pregnancy-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/pregnancy-weight-gain-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/pregnancy-conception-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/due-date-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/ovulation-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/conception-calculator', priority: 0.6, changeFrequency: 'weekly' },
    { url: '/period-calculator', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-us', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-uk', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-canada', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-australia', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-india', priority: 0.8, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-germany', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-uae', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-nigeria', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-philippines', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/tdee-calculator-russia', priority: 0.7, changeFrequency: 'weekly' },
    { url: '/blog', priority: 0.8, changeFrequency: 'daily' },
    { url: '/about', priority: 0.5, changeFrequency: 'monthly' },
    { url: '/privacy', priority: 0.4, changeFrequency: 'monthly' },
    { url: '/terms', priority: 0.4, changeFrequency: 'monthly' },
    { url: '/disclaimer', priority: 0.4, changeFrequency: 'monthly' },
    { url: '/contact', priority: 0.5, changeFrequency: 'monthly' },
  ];

  return routes.map(({ url, priority, changeFrequency }) => ({
    url: `${baseUrl}${url}`,
    lastModified: now,
    changeFrequency,
    priority,
  }));
}
